import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#f5f5f5',
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 15,
      backgroundColor: '#fff',
      borderBottomWidth: 1,
      borderBottomColor: '#ddd',
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#333',
    },
    syncButton: {
      backgroundColor: '#4287f5',
      paddingVertical: 8,
      paddingHorizontal: 15,
      borderRadius: 5,
    },
    syncButtonText: {
      color: '#fff',
      fontWeight: 'bold',
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    contentList: {
      padding: 15,
    },
    contentItem: {
      backgroundColor: '#fff',
      borderRadius: 8,
      padding: 15,
      marginBottom: 15,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    contentHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    contentTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#333',
      flex: 1,
    },
    syncStatusBadge: {
      paddingVertical: 4,
      paddingHorizontal: 8,
      borderRadius: 12,
    },
    syncStatusText: {
      color: '#fff',
      fontSize: 12,
      fontWeight: 'bold',
    },
    contentDescription: {
      fontSize: 16,
      color: '#555',
      marginBottom: 10,
    },
    contentDate: {
      fontSize: 12,
      color: '#888',
    },
    addButton: {
      position: 'absolute',
      right: 20,
      bottom: 20,
      width: 60,
      height: 60,
      backgroundColor: '#4287f5',
      borderRadius: 30,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 5,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    addButtonText: {
      fontSize: 30,
      color: '#fff',
    },
    emptyList: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    emptyText: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#888',
    },
    emptySubText: {
      fontSize: 14,
      color: '#aaa',
      marginTop: 8,
      textAlign: 'center',
    },
    centeredView: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0,0,0,0.5)',
    },
    modalView: {
      width: '80%',
      backgroundColor: 'white',
      borderRadius: 10,
      padding: 20,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 15,
      color: '#333',
      textAlign: 'center',
    },
    modalInput: {
      backgroundColor: '#f9f9f9',
      borderWidth: 1,
      borderColor: '#ddd',
      borderRadius: 5,
      padding: 10,
      marginBottom: 15,
      fontSize: 16,
    },
    textArea: {
      height: 100,
    },
    modalButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    modalButton: {
      flex: 1,
      padding: 12,
      borderRadius: 5,
      alignItems: 'center',
    },
    cancelButton: {
      backgroundColor: '#f5f5f5',
      marginRight: 10,
    },
    saveButton: {
      backgroundColor: '#4287f5',
      marginLeft: 10,
    },
    cancelButtonText: {
      color: '#333',
      fontWeight: 'bold',
    },
    saveButtonText: {
      color: '#fff',
      fontWeight: 'bold',
    },
    containerList: { flex: 1, padding: 10, backgroundColor: "#f5f5f5" },
    title: { fontSize: 24, fontWeight: "bold", textAlign: "center", marginVertical: 10 },
    listContainer: { alignItems: "center" },
    card: {
      backgroundColor: "#fff",
      borderRadius: 10,
      padding: 15,
      margin: 10,
      alignItems: "center",
      width: "45%",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 5,
    },
    image: { width: 100, height: 100, resizeMode: "contain" },
    name: { fontSize: 16, fontWeight: "bold", marginVertical: 5 },
    price: { fontSize: 14, color: "green", marginBottom: 10 },
    addButtonList: { backgroundColor: "#28a745", padding: 10, borderRadius: 5 },
    removeButton: { backgroundColor: "#dc3545", padding: 10, borderRadius: 5 },
    buttonText: { color: "white", fontWeight: "bold" },
  });
export default styles;  